name: Publish to Packagist

on:
  push:
    tags:
      - 'v*.*.*'  # 例如 v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Packagist update
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          curl -X POST \
            -u "${PACKAGIST_USERNAME}:${PACKAGIST_TOKEN}" \
            https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}
